<a href="https://colab.research.google.com/github/lav7979/Python-basics/blob/main/Data_Toolkit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1     What is NumPy, and why is it widely used in Python?

Answer:

      NumPy is a Python library for numerical computing. It provides the ndarray object for efficient storage and manipulation of large datasets. NumPy is widely used because it offers high performance, support for linear algebra, broadcasting, and vectorized operations.

Example:
      import numpy as np
       arr = np.array([1, 2, 3])

2  How does broadcasting work in NumPy?

Answer:

     Broadcasting allows operations between arrays of different shapes by automatically expanding their dimensions. It's efficient and avoids data duplication.

Example:

      a = np.array([1, 2, 3])
      b = np.array([[10], [20]])
        result = a + b  # Shape becomes (2, 3)

3  What does the term “vectorized operation” mean in NumPy?

Answer:

     Vectorized operations refer to applying operations over entire arrays without using explicit loops, leading to cleaner and faster code.

Example:

          a = np.array([1, 2, 3])
          b = a * 2  # Vectorized multiplication

4  What are the differences between NumPy arrays and Python lists?

Answer:

      Speed: NumPy arrays are faster.

       Memory: NumPy uses less memory.

      Type: NumPy arrays are homogeneous, lists are heterogeneous.

       Operations: NumPy supports elementwise operations.

Example:

          import numpy as np
          np_arr = np.array([1, 2, 3])
          py_list = [1, 2, 3]

5   How does NumPy handle multidimensional arrays?

Answer:

         NumPy supports N-dimensional arrays using the ndarray class. It allows reshaping, slicing, and mathematical operations.

Example:

        a = np.array([[1, 2], [3, 4]])
        print(a.shape)

6  Why is NumPy’s array slicing faster than Python’s list slicing?

Answer:

     NumPy arrays are stored in contiguous memory blocks and slicing creates views (not copies), making it faster.

Example:

        a = np.array([1, 2, 3, 4])
        b = a[1:3]  # Fast slice view

7   What are some advanced features of NumPy?

Answer:

      Broadcasting

      Universal functions (ufuncs)

      Structured arrays

      Random number generation

      Linear algebra with linalg


8   What is a Pandas DataFrame?

Answer:

     A DataFrame is a 2D labeled data structure with columns of different data types. It's like a table in Excel or SQL?

Example:

      import pandas as pd
      df = pd.DataFrame({'Name': ['A', 'B'], 'Age': [25, 30]})

9  Explain the use of the groupby() method in Pandas?

Answer:

groupby() groups data based on column(s) and allows applying functions like sum(), mean(), etc.

Example:

      df.groupby('Category')['Sales'].sum()

10  What is the significance of hierarchical indexing in Pandas?

Answer:

     Hierarchical indexing (MultiIndex) allows multiple levels of indexing, useful for complex datasets like panel data.

Example:

          df.set_index(['Year', 'Month'])

11  What is the purpose of the describe() function in Pandas?

Answer:

        describe() provides summary statistics (mean, std, min, etc.) of numerical columns.

Example:

      df.describe()

12  Why is handling missing data important in Pandas?

Answer:

      Missing data can bias or invalidate analysis. Pandas provides methods to detect and handle them.

Example:

      df.fillna(0)  
# Replace NaN with 0

13 Explain the difference between apply() and map() in Pandas?

Answer:


     map() is used with Series for element-wise operations.

      apply() works on Series or DataFrame and allows row/column-wise custom functions.

Example:

          df['col'].map(lambda x: x*2)
          df.apply(np.sum)

14   How does Pandas simplify time series analysis?

Answer:

     Pandas offers datetime indexing, resampling, and frequency conversion, making time series manipulation easy.

Example:

        df['Date'] = pd.to_datetime(df['Date'])
        df.set_index('Date').resample('M').sum()


15  What is the role of a pivot table in Pandas?

Answer:

     Pivot tables summarize data by reshaping it and applying aggregations.

Example:

        df.pivot_table(values='Sales', index='Region', columns='Month', aggfunc='sum')


16  Why is Seaborn preferred for statistical visualizations?

Answer:

     Seaborn provides built-in themes, simplifies complex visualizations, and integrates well with Pandas.

Example:

        import seaborn as sns
        sns.boxplot(x='category', y='value', data=df)

17  What is the role of Seaborn’s pairplot() function?

Answer:

     pairplot() plots pairwise relationships in a dataset, useful for exploring correlations and distributions.

Example:

        sns.pairplot(df)

18  What are some common use cases for Seaborn?

Answer:


       Distribution plots: distplot, kdeplot

      Categorical plots: boxplot, violinplot, barplot

      Regression plots: lmplot

      Heatmaps for correlation matrices

Example:

      sns.heatmap(df.corr(), annot=True)

19  What is a heatmap, and when should it be used?

Answer:

     A heatmap is a graphical representation of data using color to indicate values. It's used for showing correlations, matrices, or categorical intensity.

Example:

        sns.heatmap(df.corr(), cmap='coolwarm')


20   How does Matplotlib differ from Plotly?

Answer:


      Matplotlib: static plots, publication-quality.

     Plotly: interactive plots for web apps.

Example:

# Matplotlib

          import matplotlib.pyplot as plt
          plt.plot([1, 2, 3], [4, 5, 6])

# Plotly

        import plotly.express as px
        px.line(x=[1, 2, 3], y=[4, 5, 6])

21  What are the benefits of using Plotly for data visualization?

Answer:


     Interactive graphs

     Zoom, pan, tooltip support

     Easily exportable as HTML

     Works well with Dash for web apps


 22  What is the role of Bokeh in data visualization?

Answer:

     Bokeh is a library for building interactive plots and dashboards in web browsers. It supports real-time streaming and large datasets.

Example:


          from bokeh.plotting import figure, show
          p = figure(title="Line Plot")
          p.line([1, 2, 3], [4, 5, 6])
          show(p)




#Practical



1  How do you create a 2D NumPy array and calculate the sum of each row?


   import numpy as np

                arr = np.array([[1, 2, 3], [4, 5, 6]])
                row_sum = np.sum(arr, axis=1)
                print("2D Array:\n", arr)
                print("Sum of each row:", row_sum)

Output:

              2D Array:
              [[1 2 3]
              [4 5 6]]
              Sum of each row: [ 6 15]


2  Write a program to perform element-wise multiplication of two NumPy arrays?


          a = np.array([1, 2, 3])
          b = np.array([4, 5, 6])
            result = a * b
            print("Result of element-wise multiplication:", result)

Output:

        Result of element-wise multiplication: [ 4 10 18]

3 Perform matrix multiplication using NumPy?


        a = np.array([[1, 2], [3, 4]])
        b = np.array([[5, 6], [7, 8]])
            result = np.dot(a, b)
          print("Matrix Multiplication Result:\n", result)

Output:

            Matrix Multiplication Result:
            [[19 22]
            [43 50]]



4   Write a Pandas script to find the mean of a specific column in a DataFrame?


     import pandas as pd

                        df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]})
                        mean_age = df['Age'].mean()
                        print("Mean Age:", mean_age)

Output:

          Mean Age: 30.0

5  Create a DataFrame and add a new column based on an existing column?


          df['AgeGroup'] = df['Age'].apply(lambda x: 'Young' if x < 30 else 'Adult')
          print(df)

Output:


                          Name  Age AgeGroup
                    0    Alice   25    Young
                    1      Bob   30    Adult
                    2  Charlie   35    Adult

6  Generate a Pandas DataFrame and filter rows where a column value is greater than a threshold?

          filtered = df[df['Age'] > 28]
          print(filtered)


Output:


                Name  Age AgeGroup
          1      Bob   30    Adult
          2  Charlie   35    Adult

7   Use Pandas to load a CSV file and display its first 5 rows?



# Assume a file named 'data.csv' exists

                    data = pd.read_csv('data.csv')
                    print(data.head())


Output (Example):


                      Name  Age   City
                    0  John   25  Delhi
                    1  Sara   30  Mumbai
                    2  Mike   28  Pune
                    3  Lily   22  Delhi
                    4  Anna   31  Bangalore


8  Create a scatter plot using Matplotlib?


     import matplotlib.pyplot as plt

            x = [1, 2, 3, 4]
            y = [10, 20, 25, 30]

      plt.scatter(x, y, color='blue')
      plt.title('Scatter Plot')
      plt.xlabel('X')
      plt.ylabel('Y')
      plt.show()

Output:

       A scatter plot with blue dots.


9  Create a line plot with multiple lines using Matplotlib?


          x = [1, 2, 3, 4]
          y1 = [1, 4, 9, 16]
          y2 = [2, 5, 10, 17]

      plt.plot(x, y1, label='Line 1', color='green')
      plt.plot(x, y2, label='Line 2', color='red')
      plt.title('Line Plot')
      plt.xlabel('X')
      plt.ylabel('Y')
      plt.legend()
      plt.show()


Output:

      A line plot showing two lines in green and red.


10   How do you calculate the correlation matrix using Seaborn and visualize    it   with a heatmap?



      import seaborn as sns

      df = pd.DataFrame({
          'A': [1, 2, 3, 4],
          'B': [4, 5, 6, 7],
          'C': [7, 6, 5, 4]
      })

      correlation = df.corr()
      sns.heatmap(correlation, annot=True, cmap='coolwarm')
      plt.title("Correlation Heatmap")
      plt.show()

Output:

     A heatmap with correlation values.


11  Create a histogram using Seaborn to visualize a distribution?


      sns.histplot(df['B'], bins=5, kde=True, color='purple')
      plt.title('Histogram of Column B')
      plt.show()

Output:

        A histogram with a KDE line for column B.



12  Generate a bar plot using Plotly?


      import plotly.express as px

      df = pd.DataFrame({'Fruit': ['Apple', 'Banana', 'Mango'], 'Sales': [100, 150, 130]})
      fig = px.bar(df, x='Fruit', y='Sales', title="Fruit Sales")
      fig.show()

Output:

     Interactive bar plot showing fruit sales.


13  Create a 3D scatter plot using Plotly?


      import plotly.express as px

      df = pd.DataFrame({
          'x': [1, 2, 3, 4],
          'y': [10, 20, 25, 30],
          'z': [5, 15, 10, 20],
          'label': ['A', 'B', 'C', 'D']
      })

        fig = px.scatter_3d(
        df,
        x='x',
        y='y',
        z='z',
        color='category',  # Optional: color by category
        title='3D Scatter Plot Example',
        size_max=10
        )
        fig.show()
  
#Output:

      An interactive 3D scatter plot where:

      You can rotate, zoom, and pan the plot.

      Each point is placed in 3D space according to the x, y, and z values.

      Different colors indicate different category values.

